model_provider = "fox"
# 可配置gpt-5或gpt-5-codex
model = "gpt-5-codex"
# 可配置high medium low minimal
model_reasoning_effort = "high"
disable_response_storage = true
windows_wsl_setup_acknowledged = true

# foxcode配置
[model_providers.fox]
name = "fox"
base_url = "https://code.newcli.com/codex/v1"
wire_api = "responses"
requires_openai_auth = true

[projects.'\\?\D:\nobody']
trust_level = "trusted"
